version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/booking_system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0009
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=booking_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0009
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
